reading git tag should fail if no git tag exists

diff --git a/.github/workflows/tag-release.yaml b/.github/workflows/tag-release.yaml
--- a/.github/workflows/tag-release.yaml
+++ b/.github/workflows/tag-release.yaml
@@ -29,7 +29,7 @@ jobs:
         id: latest-tag
         # allow to fail as there might not be an initial tag yet
         continue-on-error: true
-        run: echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_OUTPUT
+        run: echo "LATEST_TAG=$(set -o pipefail; git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_OUTPUT
 
       - name: Get version diff
         id: version-diff
